---
- name: Установка Docker (если не установлен)
  ansible.builtin.include_role:
    name: docker

- name: Загрузка Harbor offline installer
  ansible.builtin.get_url:
    url: https://github.com/goharbor/harbor/releases/download/v2.10.2/harbor-offline-installer-v2.10.2.tgz
    dest: /tmp/harbor-offline-installer.tgz
    mode: '0644'

- name: Распаковка Harbor
  ansible.builtin.unarchive:
    src: /tmp/harbor-offline-installer.tgz
    dest: /opt/
    remote_src: true

- name: Копирование конфигурации harbor.yml
  ansible.builtin.template:
    src: harbor.yml.j2
    dest: /opt/harbor/harbor.yml
    mode: '0644'

- name: Запуск установки Harbor
  ansible.builtin.command: ./install.sh
  args:
    chdir: /opt/harbor
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  changed_when: true
