---
- name: Create argocd namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present

- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    namespace: argocd
    create_namespace: false
    values:
      server:
        extraArgs:
          - --insecure
        ingress:
          enabled: true
          hosts:
            - argocd.local
        adminPassword: admin123
      configs:
        secret:
          argocdServerAdminPassword: $2a$10$rRyBsGSHK6.uc8fntPwVIuLVHXAhX4q9zK.Om2DqD9CwDWiGDtUu2