---
- name: Install local-path-provisioner
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: local-path-provisioner
        namespace: kube-system
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: local-path-provisioner
        template:
          metadata:
            labels:
              app: local-path-provisioner
          spec:
            serviceAccountName: local-path-provisioner-service-account
            containers:
              - name: local-path-provisioner
                image: rancher/local-path-provisioner:v0.0.24
                args:
                  - --debug
                  - start
                  - --config
                  - /etc/config/config.json
                volumeMounts:
                  - name: config-volume
                    mountPath: /etc/config/
            volumes:
              - name: config-volume
                configMap:
                  name: local-path-config

- name: Create local-path-provisioner ServiceAccount
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: local-path-provisioner-service-account
        namespace: kube-system

- name: Create local-path-provisioner ClusterRole
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: local-path-provisioner-role
      rules:
        - apiGroups: [""]
          resources: ["nodes", "persistentvolumeclaims", "persistentvolumes"]
          verbs: ["get", "list", "watch"]
        - apiGroups: [""]
          resources: ["persistentvolumeclaims", "endpoints"]
          verbs: ["get", "list", "watch", "update", "create"]
        - apiGroups: [""]
          resources: ["persistentvolumes"]
          verbs: ["get", "list", "watch", "update", "create", "delete"]
        - apiGroups: [""]
          resources: ["events"]
          verbs: ["watch", "create", "update", "patch"]
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list", "watch"]

- name: Create local-path-provisioner ClusterRoleBinding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: local-path-provisioner-bind
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: local-path-provisioner-role
      subjects:
        - kind: ServiceAccount
          name: local-path-provisioner-service-account
          namespace: kube-system

- name: Create local-path-provisioner ConfigMap
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: local-path-config
        namespace: kube-system
      data:
        config.json: |
          {
            "nodePathMap":[
            {
              "node": "DEFAULT_PATH_FOR_NON_EXISTING_NODES",
              "paths": ["/var/lib/rancher/k3s/storage"]
            }
            ],
            "setup": false
          }

- name: Create local-path StorageClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: rancher.io/local-path
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete 