---
# Основной Ansible playbook для DevOps_playbook-main

- name: Установка Harbor
  hosts: harbor
  become: true
  roles:
    - harbor

- name: Подготовка всех нод
  hosts: rke2
  gather_facts: false
  become: true
  roles:
    - prepare-nodes
    - rke2-download

- name: Установка Kube VIP
  hosts: servers
  gather_facts: true
  roles:
    - kube-vip

- name: Подготовка RKE2 на серверах и агентах
  hosts: servers,agents
  gather_facts: true
  roles:
    - rke2-prepare

- name: Добавление дополнительных RKE2 серверов
  hosts: servers
  gather_facts: true
  roles:
    - add-server

- name: Добавление агентов в кластер
  hosts: agents
  gather_facts: true
  roles:
    - add-agent

- name: Применение манифестов после создания кластера
  hosts: servers
  gather_facts: true
  roles:
    - apply-manifests

- name: Настройка инфраструктуры (storage, ingress)
  hosts: servers
  gather_facts: true
  roles:
    - storage
    - ingress

- name: Установка мониторинга (Prometheus + Grafana)
  hosts: servers
  gather_facts: true
  roles:
    - prometheus
    - loki

- name: Установка ArgoCD для GitOps
  hosts: servers
  gather_facts: true
  roles:
    - argocd

- name: Настройка ingress-правил для сервисов
  hosts: servers
  gather_facts: true
  roles:
    - ingress-rules
