---
- name: Add Grafana Helm repository
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Install Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    namespace: monitoring
    create_namespace: false
    values:
      loki:
        auth_enabled: false
        storage:
          type: filesystem
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
        persistence:
          enabled: true
          storageClassName: local-path
          size: 10Gi
